#!/usr/bin/env bash
# shellcheck disable=SC2046,SC2086,SC2089,SC2090
set -e

SCRIPT_DIR=$(dirname "$(realpath "$0")")
local_repo=$HOME/.local/packages
cleaner=$HOME/bin/termux-junk-cleaner

# Colours functions
function cecho() {
    local code="\033["
    case $1 in
        black  | bk) color="${code}0;30m";;
        red    |  r) color="${code}1;31m";;
        green  |  g) color="${code}1;32m";;
        yellow |  y) color="${code}0;33m";;
        blue   |  b) color="${code}0;34m";;
        purple |  p) color="${code}0;35m";;
        cyan   |  c) color="${code}0;36m";;
        gray   | gr) color="${code}0;37m";;
        *) local text="$1"
    esac
    [[ $text ]] || local text="$color$2${code}0m"
    echo -e "$text"
}

# Package managers check
if [ -n "$(command -v apt)" ]; then
    package='apt'
    change_repo="termux-change-repo"
    local_packages="dpkg -i ${local_repo}/debian/*.deb"
    clean_packages="pkg autoclean && pkg clean"
elif [ -n "$(command -v pacman)" ]; then
    package='pacman'
    change_repo="nano $PREFIX/etc/pacman.conf"
    local_packages="pacman -U ${local_repo}/pacman/*.pkg.tar.xz --noconfirm"
    clean_packages="pacman -Scc"
fi

# Function to print success message
success_msg() {
    cecho c "\n► Init completed. \n"
}

cecho g "\n► Give storage access\n"
select strictreply in "Yes" "No"; do
    relaxedreply=${strictreply:-$REPLY}
    case $relaxedreply in
        Yes | yes | y ) termux-setup-storage; break;;
        No  | no  | n ) break;;
    esac
done

cecho g "\n► Turn on wakelock?\n"
select strictreply in "Yes" "No"; do
    relaxedreply=${strictreply:-$REPLY}
    case $relaxedreply in
        Yes | yes | y ) termux-wake-lock; break;;
        No  | no  | n ) break;;
    esac
done

cecho g "\n► Change repo?\n"
select strictreply in "Yes" "No"; do
    relaxedreply=${strictreply:-$REPLY}
    case $relaxedreply in
        Yes | yes | y ) ${change_repo}; break;;
        No  | no  | n ) break;;
    esac
done

cecho g "\n► Start full system update?\n"
select strictreply in "Yes" "No"; do
    relaxedreply=${strictreply:-$REPLY}
    case $relaxedreply in
        Yes | yes | y ) pkg update && pkg upgrade -y; break;;
        No  | no  | n ) break;;
    esac
done

if [ -n "$(command -v apt)" ]; then
    cecho g "\n► Add additional repository?\n"
    select strictreply in "Yes" "No"; do
        relaxedreply=${strictreply:-$REPLY}
        case $relaxedreply in
            Yes | yes | y ) pkg install -y $(cat "$SCRIPT_DIR/repo.txt" | grep -vP '^(?:\s+)?#'); break;;
            No  | no  | n ) break;;
        esac
    done
fi

if [ -n "$(command -v apt)" ]; then
    if [[ -f "$SCRIPT_DIR/tur.list" ]]; then
        cecho r "\n► Modify repo source?\n"
        select strictreply in "Yes" "No"; do
            relaxedreply=${strictreply:-$REPLY}
            case $relaxedreply in
                Yes | yes | y ) cp "$SCRIPT_DIR/tur.list" "$PREFIX/etc/apt/sources.list.d"; pkg update && pkg upgrade -y; break;;
                No  | no  | n ) break;;
            esac
        done
    fi
fi

if [[ -f "$SCRIPT_DIR/pkg-${package}.txt" ]]; then
    if [ -n "$(command -v apt)" ]; then
        cecho g "\n► Install necessary packages?\n"
        select strictreply in "Yes" "No"; do
            relaxedreply=${strictreply:-$REPLY}
            case $relaxedreply in
                Yes | yes | y ) pkg install -y $(cat "$SCRIPT_DIR/pkg-${package}.txt" | grep -vP '^(?:\s+)?#'); break;;
                No  | no  | n ) break;;
            esac
        done
    elif [ -n "$(command -v pacman)" ]; then
        cecho g "\n► Install necessary packages?\n"
        select strictreply in "Yes" "No"; do
            relaxedreply=${strictreply:-$REPLY}
            case $relaxedreply in
                Yes | yes | y ) grep -vP '^(?:\s+)?#' $SCRIPT_DIR/pkg-${package}.txt | pacman -S --noconfirm --needed -; break;;
                No  | no  | n ) break;;
            esac
        done
    fi
fi

if [ -n "$(command -v pacman)" ]; then
    cecho g "\n► Install base devel package?\n"
    select strictreply in "Yes" "No"; do
        relaxedreply=${strictreply:-$REPLY}
        case $relaxedreply in
            Yes | yes | y ) pacman -S base-devel; break;;
            No  | no  | n ) break;;
        esac
    done
fi

cecho g "\n► Install local python packages?\n"
cecho y "► Put your package(s) into packages/pip dir\n"
select strictreply in "Yes" "No"; do
    relaxedreply=${strictreply:-$REPLY}
    case $relaxedreply in
        Yes | yes | y ) pip install --no-cache-dir -r $SCRIPT_DIR/requirements.txt; pip2 install ${local_repo}/python/unrpyc-1.3.2.tar.gz; break;;
        No  | no  | n ) break;;
    esac
done

cecho g "\n► Install local packages?\n"
cecho y "► Put your package(s) into packages/(apt | pacman) dir\n"
select strictreply in "Yes" "No"; do
    relaxedreply=${strictreply:-$REPLY}
    case $relaxedreply in
        Yes | yes | y ) ${local_packages}; break;;
        No  | no  | n ) break;;
    esac
done

cecho g "\n► Clean packages cache?\n"
select strictreply in "Yes" "No"; do
    relaxedreply=${strictreply:-$REPLY}
    case $relaxedreply in
        Yes | yes | y ) ${clean_packages}; pip cache purge; break;;
        No  | no  | n ) break;;
    esac
done

if [[ -f "$cleaner" ]]; then
    cecho g "\n► Run cleaner?\n"
    select strictreply in "Yes" "No"; do
        relaxedreply=${strictreply:-$REPLY}
        case $relaxedreply in
            Yes | yes | y ) bash $cleaner -y; break;;
            No  | no  | n ) break;;
        esac
    done
fi

cecho g "\n► Turn off wakelock?\n"
select strictreply in "Yes" "No"; do
    relaxedreply=${strictreply:-$REPLY}
    case $relaxedreply in
        Yes | yes | y ) termux-wake-unlock; break;;
        No  | no  | n ) break;;
    esac
done

success_msg
exit
